// app/layout.tsx
import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import {ThemeProvider} from "next-themes";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="fr" suppressHydrationWarning>
        <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="system">
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
